version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_PATH=/app/data/game.db
    volumes:
      - ./backend/src:/app/src
      - ./database:/app/data
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules_frontend:
  node_modules_backend:
  database_data:
